# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
# If you want to automatically update fastlane if a new version is available:
update_fastlane
fastlane_version "2.28.4"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :prd do
    increment_build_number
    commit_version_bump(force: true, xcodeproj: "screenshot.xcodeproj")
    push_to_git_remote

    gym(scheme: "prdScreenshot") # Build your app - more options available
    testflight(skip_waiting_for_build_processing: true) # to only upload the build
    version = get_version_number(xcodeproj: "screenshot.xcodeproj", target: "screenshot", configuration: "prdRelease")
    add_git_tag(tag: "#{version}/#{lane_context[SharedValues::BUILD_NUMBER]}")
    push_to_git_remote
  end

  lane :dev do
    increment_build_number
    commit_version_bump(force: true, xcodeproj: "screenshot.xcodeproj")
    push_to_git_remote

    gym(scheme: "devScreenshot") # Build your app - more options available
    testflight(skip_waiting_for_build_processing: true, app_identifier: "io.crazeapp.screenshot.dev") # to only upload the build
    version = get_version_number
    add_git_tag(tag: "#{version}/#{lane_context[SharedValues::BUILD_NUMBER]}")
    push_to_git_remote
  end

end
