//
//  Random.swift
//  screenshot
//
//  Created by Jonathan Rose on 4/11/18.
//  Copyright © 2018 crazeapp. All rights reserved.
//

import Foundation

extension Collection where Index == Int {
    
    /**
     Picks a random element of the collection.
     
     - returns: A random element of the collection.
     */
    func randomElement() -> Iterator.Element? {
        return isEmpty ? nil : self[Int(arc4random_uniform(UInt32(endIndex)))]
    }
 
}

extension MutableCollection {
    /// Shuffles the contents of this collection.
    mutating func shuffle() {
        let c = count
        guard c > 1 else { return }
        
        for (firstUnshuffled, unshuffledCount) in zip(indices, stride(from: c, to: 1, by: -1)) {
            // Change `Int` in the next line to `IndexDistance` in < Swift 4.1
            let d: Int = numericCast(arc4random_uniform(numericCast(unshuffledCount)))
            let i = index(firstUnshuffled, offsetBy: d)
            swapAt(firstUnshuffled, i)
        }
    }
}

extension Sequence {
    /// Returns an array with the contents of this sequence, shuffled.
    func shuffled() -> [Element] {
        var result = Array(self)
        result.shuffle()
        return result
    }
}

extension String {
    static func randomFemaleName() -> String{
        let femaleNames = ["Aaliyah",",
            ""Abby",
            "Abigail",
            "Abril",
            "Ada",
            "Adaline",
            "Adalyn",
            "Adalynn",
            "Addilyn",
            "Addilynn",
            "Addison",
            "Addisyn",
            "Addyson",
            "Adelaide",
            "Adele",
            "Adelina",
            "Adeline",
            "Adelyn",
            "Adelynn",
            "Adilynn",
            "Adley",
            "Adriana",
            "Adrianna",
            "Adrienne",
            "Aileen",
            "Aimee",
            "Ainsley",
            "Aisha",
            "Aislinn",
            "Aitana",
            "Aiyana",
            "Alaia",
            "Alaina",
            "Alana",
            "Alani",
            "Alanna",
            "Alannah",
            "Alaya",
            "Alayah",
            "Alayna",
            "Aleah",
            "Aleena",
            "Alejandra",
            "Alena",
            "Alessandra",
            "Alexa",
            "Alexandra",
            "Alexandria",
            "Alexia",
            "Alexis",
            "Alexus",
            "Alia",
            "Aliana",
            "Alianna",
            "Alice",
            "Alicia",
            "Alina",
            "Alisha",
            "Alison",
            "Alissa",
            "Alisson",
            "Alivia",
            "Aliya",
            "Aliyah",
            "Aliza",
            "Alizah",
            "Allie",
            "Allison",
            "Ally",
            "Allyson",
            "Alma",
            "Alondra",
            "Alyson",
            "Alyssa",
            "Amalia",
            "Amanda",
            "Amani",
            "Amani",
            "Amara",
            "Amari",
            "Amaris",
            "Amaya",
            "Amber",
            "Amelia",
            "Amelie",
            "America",
            "Amia",
            "Amina",
            "Aminah",
            "Amira",
            "Amirah",
            "Amiya",
            "Amiyah",
            "Amy",
            "Amy",
            "Amya",
            "Ana",
            "Anabella",
            "Anabelle",
            "Anahi",
            "Analia",
            "Anastasia",
            "Anaya",
            "Andi",
            "Andrea",
            "Angel",
            "Angela",
            "Angelica",
            "Angelina",
            "Angeline",
            "Angelique",
            "Angie",
            "Anika",
            "Aniya",
            "Aniyah",
            "Ann",
            "Anna",
            "Annabel",
            "Annabella",
            "Annabelle",
            "Annalee",
            "Annalise",
            "Anne",
            "Annie",
            "Annika",
            "Ansley",
            "Antonia",
            "Anya",
            "April",
            "April",
            "Arabella",
            "Aranza",
            "Arden",
            "Arely",
            "Aria",
            "Ariadne",
            "Ariah",
            "Ariana",
            "Arianna",
            "Ariel",
            "Ariella",
            "Arielle",
            "Ariya",
            "Ariyah",
            "Armani",
            "Arya",
            "Aryana",
            "Aryanna",
            "Ashlee",
            "Ashley",
            "Ashlyn",
            "Ashlynn",
            "Asia",
            "Aspen",
            "Astrid",
            "Athena",
            "Aubree",
            "Aubrey",
            "Aubrianna",
            "Aubrie",
            "Aubriella",
            "Aubrielle",
            "Audrey",
            "Audrina",
            "Augusta",
            "Aurelia",
            "Aurora",
            "Autumn",
            "Ava",
            "Avah",
            "Avalyn",
            "Avalynn",
            "Averi",
            "Averie",
            "Avery",
            "Aviana",
            "Avianna",
            "Avril",
            "Aya",
            "Ayla",
            "Ayleen",
            "Aylin",
            "Azalea",
            "Azaleah",
            "Azaria",
            "Azariah",
            "Bailee",
            "Bailey",
            "Barbara",
            "Baylee",
            "Bea",
            "Beatrice",
            "Becca",
            "Becky",
            "Beka",
            "Belen",
            "Belinda",
            "Bella",
            "Bethany",
            "Betty",
            "Beverly",
            "Bianca",
            "Blair",
            "Blake",
            "Blakely",
            "Blanca",
            "Bonnie",
            "Braelyn",
            "Braelynn",
            "Braylee",
            "Breanna",
            "Brenda",
            "Brenna",
            "Bria",
            "Briana",
            "Brianna",
            "Briar",
            "Bridget",
            "Bridget",
            "Briella",
            "Brielle",
            "Briley",
            "Brinley",
            "Bristol",
            "Brittany",
            "Brook",
            "Brooke",
            "Brooklyn",
            "Brooklynn",
            "Bryanna",
            "Brylee",
            "Bryleigh",
            "Brynlee",
            "Brynn",
            "Cadence",
            "Caitlin",
            "Caitlyn",
            "Cali",
            "Callie",
            "Cameron",
            "Cameryn",
            "Camila",
            "Camilla",
            "Camille",
            "Camryn",
            "Cara",
            "Carla",
            "Carlee",
            "Carly",
            "Carly",
            "Carmen",
            "Carol",
            "Carolina",
            "Caroline",
            "Carolyn",
            "Carter",
            "Casey",
            "Cassandra",
            "Cassidy",
            "Cataleya",
            "Catalina",
            "Catherine",
            "Cathy",
            "Caylee",
            "Cecelia",
            "Cecilia",
            "Celeste",
            "Celia",
            "Celina",
            "Celine",
            "Chana",
            "Chanel",
            "Charlee",
            "Charleigh",
            "Charley",
            "Charli",
            "Charlie",
            "Charlize",
            "Charlotte",
            "Chaya",
            "Chelly",
            "Chelsea",
            "Cherish",
            "Cheryl",
            "Cheyenne",
            "Chloe",
            "Christina",
            "Christine",
            "Ciara",
            "Claire",
            "Clara",
            "Clare",
            "Clarissa",
            "Claudia",
            "Clementine",
            "Colette",
            "Collins",
            "Coraline",
            "Cordelia",
            "Corinne",
            "Courtney",
            "Courtney",
            "Crystal",
            "Cynthia",
            "Dahlia",
            "Daisy",
            "Daisy",
            "Dakota",
            "Dalary",
            "Daleyza",
            "Dallas",
            "Dana",
            "Danica",
            "Daniela",
            "Daniella",
            "Danielle",
            "Danna",
            "Daphne",
            "Dawn",
            "Dayana",
            "Debbie",
            "Deborah",
            "Debra",
            "Deja",
            "Delaney",
            "Delilah",
            "Demi",
            "Demi",
            "Denise",
            "Desiree",
            "Destiny",
            "Destiny",
            "Diamond",
            "Diana",
            "Diane",
            "Dianna",
            "Dianne",
            "Dixie",
            "Donna",
            "Doris",
            "Dorothy",
            "Dulce",
            "Dylan",
            "Ebony",
            "Eden",
            "Eden",
            "Edith",
            "Edith",
            "Eileen",
            "Elaina",
            "Elaine",
            "Eleanor",
            "Elena",
            "Eliana",
            "Elianna",
            "Elicia",
            "Elin",
            "Elisa",
            "Elisabeth",
            "Elise",
            "Eliza",
            "Elizabeth",
            "Ella",
            "Elle",
            "Ellen",
            "Elliana",
            "Ellie",
            "Elliot",
            "Elliott",
            "Ellis",
            "Ellison",
            "Eloise",
            "Elora",
            "Elsa",
            "Elsie",
            "Elyse",
            "Ember",
            "Emelia",
            "Emely",
            "Emerie",
            "Emerson",
            "Emersyn",
            "Emery",
            "Emilee",
            "Emilia",
            "Emilie",
            "Emily",
            "Emma",
            "Emmalee",
            "Emmaline",
            "Emmalyn",
            "Emmalynn",
            "Emmeline",
            "Emmy",
            "Emmy",
            "Emory",
            "Erica",
            "Erika",
            "Erin",
            "Esme",
            "Esmeralda",
            "Esperanza",
            "Estela",
            "Estella",
            "Estelle",
            "Esther",
            "Estrella",
            "Eva",
            "Evalyn",
            "Evangeline",
            "Eve",
            "Evelyn",
            "Evelynn",
            "Everleigh",
            "Everly",
            "Evie",
            "Faith",
            "Farrah",
            "Fatema",
            "Fatima",
            "Faye",
            "Fayth",
            "Felicia",
            "Felicity",
            "Fernanda",
            "Finley",
            "Fiona",
            "Florence",
            "Florencia",
            "Frances",
            "Francesca",
            "Frankie",
            "Freya",
            "Frida",
            "Gabbi",
            "Gabriela",
            "Gabriella",
            "Gabrielle",
            "Gail",
            "Galilea",
            "Gemma",
            "Genevieve",
            "Georgia",
            "Gia",
            "Giana",
            "Gianna",
            "Giavanna",
            "Gigi",
            "Gina",
            "Giovanna",
            "Giselle",
            "Giuliana",
            "Gloria",
            "Grace",
            "Gracelyn",
            "Gracelynn",
            "Gracie",
            "Greta",
            "Guadalupe",
            "Gwen",
            "Gwendolyn",
            "Hadassah",
            "Hadlee",
            "Hadleigh",
            "Hadley",
            "Hailee",
            "Hailey",
            "Haley",
            "Halle",
            "Hallie",
            "Hana",
            "Hanna",
            "Hannah",
            "Harlee",
            "Harley",
            "Harlow",
            "Harmoni",
            "Harmony",
            "Harmony",
            "Harper",
            "Harper",
            "Harriet",
            "Hattie",
            "Haven",
            "Hayden",
            "Haylee",
            "Hayley",
            "Hazell",
            "Heather",
            "Heaven",
            "Heavenly",
            "Heidi",
            "Helen",
            "Helena",
            "Henley",
            "Holland",
            "Holly",
            "Holly",
            "Hope",
            "Hunter",
            "Ida",
            "Iliana",
            "Imani",
            "Imani",
            "Imogen",
            "Ingrid",
            "Ireland",
            "Irene",
            "Iris",
            "Isabel",
            "Isabela",
            "Isabella",
            "Isadora",
            "Isla",
            "Itzel",
            "Ivanka",
            "Ivanna",
            "Ivory",
            "Ivy",
            "Ivy",
            "Izabella",
            "Jacqueline",
            "Jada",
            "Jade",
            "Jaelyn",
            "Jaelynn",
            "Jaida",
            "Jaime",
            "Jaliyah",
            "Jamie",
            "Janae",
            "Jane",
            "Janelle",
            "Janessa",
            "Janet",
            "Janice",
            "Janiya",
            "Janiyah",
            "Jasmin",
            "Jasmine",
            "Jaycee",
            "Jayda",
            "Jayde",
            "Jayden",
            "Jayla",
            "Jaylah",
            "Jaylee",
            "Jayleen",
            "Jaylene",
            "Jaylin",
            "Jaylynn",
            "Jazlyn",
            "Jazlynn",
            "Jazmin",
            "Jazmine",
            "Jean",
            "Jemma",
            "Jenna",
            "Jennifer",
            "Jenny",
            "Jessa",
            "Jessica",
            "Jessie",
            "Jewel",
            "Jill",
            "Jillian",
            "Jimena",
            "Joan",
            "Joanna",
            "Jocelyn",
            "Jocelynn",
            "Johanna",
            "Jolene",
            "Jolie",
            "Jordan",
            "Jordyn",
            "Jordynn",
            "Joselyn",
            "Josephine",
            "Josie",
            "Joslyn",
            "Journee",
            "Journey",
            "Joy",
            "Joyce",
            "Judith",
            "Judy",
            "Jules",
            "Julia",
            "Juliana",
            "Julianna",
            "Julianne",
            "Julie",
            "Juliet",
            "Julieta",
            "Juliette",
            "Julissa",
            "June",
            "Juniper",
            "Justice",
            "Kadence",
            "Kaelyn",
            "Kaelynn",
            "Kai",
            "Kaia",
            "Kaila",
            "Kailani",
            "Kailee",
            "Kailey",
            "Kailyn",
            "Kairi",
            "Kaitlyn",
            "Kaitlynn",
            "Kaiya",
            "Kalani",
            "Kali",
            "Kaliyah",
            "Kallie",
            "Kamila",
            "Kamryn",
            "Kara",
            "Karen",
            "Karina",
            "Karla",
            "Karlee",
            "Karlie",
            "Karsyn",
            "Karter",
            "Kassandra",
            "Kassidy",
            "Katalina",
            "Kate",
            "Katelyn",
            "Katelynn",
            "Katherine",
            "Kathleen",
            "Kathryn",
            "Katie",
            "Katie",
            "Kaya",
            "Kayden",
            "Kaydence",
            "Kayla",
            "Kaylee",
            "Kayleigh",
            "Kaylie",
            "Kaylin",
            "Kaylyn",
            "Kaylynn",
            "Keira",
            "Kelly",
            "Kelsey",
            "Kelsey",
            "Kendall",
            "Kendra",
            "Kenia",
            "Kenley",
            "Kenna",
            "Kennedi",
            "Kennedy",
            "Kensington",
            "Kensley",
            "Kenya",
            "Kenzie",
            "Keyla",
            "Khaleesi",
            "Khloe",
            "Kiana",
            "Kiara",
            "Kiera",
            "Kiley",
            "Kim",
            "Kimber",
            "Kimberly",
            "Kimora",
            "Kinley",
            "Kinslee",
            "Kinsley",
            "Kira",
            "Kirstie",
            "Klara",
            "Kora",
            "Kori",
            "Kristen",
            "Kristina",
            "Kyla",
            "Kylee",
            "Kyleigh",
            "Kylie",
            "Kyndall",
            "Kynlee",
            "Kyra",
            "Lacey",
            "Laila",
            "Lailah",
            "Lainey",
            "Lana",
            "Landry",
            "Laney",
            "Lara",
            "Laura",
            "Laurel",
            "Lauren",
            "Lauryn",
            "Layla",
            "Laylah",
            "Lea",
            "Leah",
            "Leanna",
            "Leia",
            "Leighton",
            "Leila",
            "Leilani",
            "Lena",
            "Lennon",
            "Lennox",
            "Leona",
            "Leslie",
            "Lexi",
            "Lexie",
            "Leyla",
            "Lia",
            "Liana",
            "Libby",
            "Liberty",
            "Lila",
            "Lilah",
            "Lilia",
            "Lilian",
            "Liliana",
            "Lilianna",
            "Lilith",
            "Lillian",
            "Lilliana",
            "Lillianna",
            "Lillie",
            "Lilly",
            "Lilly",
            "Lily",
            "Lilyana",
            "Lilyanna",
            "Lina",
            "Linda",
            "Lindsay",
            "Lindsey",
            "Lisa",
            "Liv",
            "Livia",
            "Lizbeth",
            "Lizbeth",
            "Lizzy",
            "Logan",
            "Lola",
            "London",
            "Londyn",
            "Lorelai",
            "Lorelei",
            "Lori",
            "Louisa",
            "Lucia",
            "Luciana",
            "Lucie",
            "Lucille",
            "Lucy",
            "Luna",
            "Luz",
            "Lydia",
            "Lyla",
            "Lylah",
            "Lynne",
            "Lyra",
            "Lyric",
            "MaKayla",
            "Mabel",
            "Maci",
            "Macie",
            "Mackenzie",
            "Macy",
            "Madalyn",
            "Madalynn",
            "Maddison",
            "Madeleine",
            "Madelyn",
            "Madelynn",
            "Madilyn",
            "Madilynn",
            "Madison",
            "Madisyn",
            "Madyson",
            "Mae",
            "Maeve",
            "Maggie",
            "Magnolia",
            "Maia",
            "Maisie",
            "Makayla",
            "Makenna",
            "Makenzie",
            "Malaya",
            "Malaysia",
            "Maleah",
            "Malia",
            "Maliah",
            "Maliah",
            "Maliyah",
            "Mallory",
            "Mara",
            "Maree",
            "Margaret",
            "Margot",
            "Maria",
            "Mariah",
            "Mariam",
            "Mariana",
            "Marianna",
            "Marie",
            "Marilyn",
            "Marina",
            "Marisol",
            "Marissa",
            "Mariyah",
            "Marjorie",
            "Marlee",
            "Marleigh",
            "Marley",
            "Martha",
            "Mary",
            "Maryam",
            "Matilda",
            "May",
            "Maya",
            "Mckenna",
            "Mckenzie",
            "Mckinley",
            "Meadow",
            "Megan",
            "Meilani",
            "Melanie",
            "Melany",
            "Melina",
            "Melissa",
            "Melody",
            "Meredith",
            "Mia",
            "Miah",
            "Micaelah",
            "Micah",
            "Michaela",
            "Michelle",
            "Mikaela",
            "Mikayla",
            "Mila",
            "Milan",
            "Milana",
            "Milani",
            "Milania",
            "Milena",
            "Millie",
            "Mina",
            "Mira",
            "Miracle",
            "Miranda",
            "Miriam",
            "Miya",
            "Molly",
            "Molly",
            "Monica",
            "Monroe",
            "Monserrat",
            "Montserrat",
            "Morgan",
            "Moriah",
            "Mya",
            "Myah",
            "Myla",
            "Myra",
            "Nadia",
            "Nala",
            "Nancy",
            "Naomi",
            "Natalee",
            "Natalia",
            "Natalie",
            "Nataly",
            "Natasha",
            "Nathalia",
            "Nathalie",
            "Nathaly",
            "Naya",
            "Nayeli",
            "Neriah",
            "Nevaeh",
            "Nia",
            "Nicole",
            "Nikki",
            "Nina",
            "Noa",
            "Noah",
            "Noelle",
            "Noemi",
            "Nola",
            "Noor",
            "Nora",
            "Norah",
            "Nova",
            "Nyla",
            "Nylah",
            "Oakley",
            "Olive",
            "Olivia",
            "Ophelia",
            "Paige",
            "Paislee",
            "Paisley",
            "Paityn",
            "Paloma",
            "Pamela",
            "Paola",
            "Paris",
            "Parker",
            "Patricia",
            "Patty",
            "Paula",
            "Paulina",
            "Payton",
            "Pearl",
            "Penelope",
            "Penny",
            "Perla",
            "Peyton",
            "Phoebe",
            "Phoenix",
            "Piper",
            "Piper",
            "Polly",
            "Poppy",
            "Precious",
            "Presley",
            "Princess",
            "Priscilla",
            "Quinn",
            "Quinn",
            "Rachel",
            "Raegan",
            "Raelyn",
            "Raelynn",
            "Rafaela",
            "Raina",
            "Raquel",
            "Raven",
            "Rayna",
            "Reagan",
            "Rebecca",
            "Rebekah",
            "Reese",
            "Regina",
            "Reina",
            "Remi",
            "Remington",
            "Remy",
            "Renata",
            "Reyna",
            "Rhea",
            "Rhianna",
            "Rikki",
            "Riley",
            "River",
            "Rivka",
            "Rochelle",
            "Romina",
            "Rory",
            "Rosa",
            "Rosalie",
            "Rose",
            "Roselyn",
            "Rosemary",
            "Rosie",
            "Rowan",
            "Royal",
            "Ruby",
            "Ruby",
            "Ruth",
            "Ryan",
            "Ryann",
            "Rylan",
            "Rylee",
            "Ryleigh",
            "Rylie",
            "Sabrina",
            "Sadie",
            "Sage",
            "Saige",
            "Salma",
            "Samantha",
            "Samara",
            "Sandra",
            "Saniyah",
            "Sara",
            "Sarah",
            "Sarahi",
            "Sarai",
            "Sariah",
            "Sariyah",
            "Sasha",
            "Savanna",
            "Savannah",
            "Sawyer",
            "Saylor",
            "Scarlet",
            "Scarlett",
            "Scarlette",
            "Selah",
            "Selena",
            "Serena",
            "Serenity",
            "Shania",
            "Shanice",
            "Shannice",
            "Sharon",
            "Shayla",
            "Shelby",
            "Sheniqua",
            "Shenique",
            "Shiloh",
            "Shirley",
            "Sidney",
            "Siena",
            "Sienna",
            "Sierra",
            "Simone",
            "Sky",
            "Skye",
            "Skyla",
            "Skylar",
            "Skyler",
            "Sloan",
            "Sloane",
            "Sofia",
            "Sophia",
            "Sophie",
            "Stella",
            "Stephanie",
            "Stevie",
            "Summer",
            "Summer",
            "Susan",
            "Sutton",
            "Sydney",
            "Sylvia",
            "Tabitha",
            "Talia",
            "Taliyah",
            "Tamar",
            "Tammy",
            "Tara",
            "Tatiana",
            "Tatum",
            "Taya",
            "Taylor",
            "Teagan",
            "Teagen",
            "Tegan",
            "Tenley",
            "Teresa",
            "Tessa",
            "Thalia",
            "Thea",
            "Thea",
            "Theresa",
            "Tia",
            "Tiana",
            "Tianna",
            "Tiara",
            "Tierra",
            "Tiffany",
            "Tiffany",
            "Tinley",
            "Toni",
            "Tori",
            "Trinity",
            "Valentina",
            "Valeria",
            "Valerie",
            "Vanessa",
            "Veda",
            "Vera",
            "Veronica",
            "Vicky",
            "Victoria",
            "Vienna",
            "Violet",
            "Violet",
            "Virginia",
            "Viviana",
            "Vivienne",
            "Wendy",
            "Whitney",
            "Willa",
            "Willow",
            "Winter",
            "Wren",
            "Wynter",
            "Ximena",
            "Yamileth",
            "Yareli",
            "Yaretzi",
            "Yaritza",
            "Yasmin",
            "Yesenia",
            "Yolanda",
            "Zahra",
            "Zainab",
            "Zaniyah",
            "Zara",
            "Zaria",
            "Zariah",
            "Zariyah",
            "Zaylee",
            "Zelda",
            "Zendaya",
            "Zion",
            "Zoe",
            "Zoey",
            "Zoie",
            "Zuri"]
        return femaleNames.randomElement() ?? "Molly"
    }
    static func randomMaleName() -> String{
        let maleNames = [
            "John",
            "Robert",
            "Michael",
            "Will",
            "David",
            "Richard",
            "Joseph",
            "Tom",
            "Charlie",
            "Christopher",
            "Daniel",
            "Matthew",
            "Anthony",
            "Liam",
            "Mark",
            "Paul",
            "Steven",
            "Andrew",
            "Ken",
            "George",
            "Josh",
            "Kevin",
            "Brian",
            "Edward",
            "Ronald",
            "Timothy",
            "Jason",
            "Jeffrey",
            "Ryan",
            "Gary",
            "Jacob",
            "Nick",
            "Eric",
            "Stephen",
            "Jonathan",
            "Larry",
            "Justin",
            "Scott",
            "Frank",
            "Brandon",
            "Raymond",
            "Greg",
            "Benjamin",
            "Sammy",
            "Patrick",
            "Alexander",
            "Jack",
            "Dennis",
            "Jerry",
            "Tyler",
            "Aaron",
            "Henry",
            "Douglas",
            "Jose",
            "Peter",
            "Adam",
            "Zachary",
            "Nathan",
            "Walter",
            "Harry",
            "Kyle",
            "Carl",
            "Arthur",
            "Noah",
            "Roger",
            "Keith",
            "Jeremy",
            "Terry",
            "Lawrence",
            "Sean",
            "Christian",
            "Albert",
            "Joe",
            "Ethan",
            "Austin",
            "Jesse",
            "Willie",
            "Billy",
            "Bryan",
            "Bruce",
            "Jordan",
            "Ralph",
            "Roy",
            "Noah",
            "Dylan",
            "Eugene",
            "Wayne",
            "Alan",
            "Juan",
            "Louis",
            "Russell",
            "Gabriel",
            "Randy",
            "Philip",
            "Harry",
            "Bobby",
            "Johnny",
            "Logan",
            "Johnny ",
            "Danny ",
            "Matt"]
        return maleNames.randomElement() ?? "Matt"

    }
    static func randomName() -> String{
        let percentFemale:Double = 0.9
        let max = 10000
        
        let isFemale = (arc4random_uniform(10000) < Int(Double(max) * percentFemale))
        if isFemale {
            return String.randomFemaleName()
        }else{
            return String.randomMaleName()
        }
    }
    static func randomCity() -> String{
        let cities = ["New York, New York",
                      "Los Angeles, California",
                      "Chicago, Illinois",
                      "Houston, Texas",
                      "Philadelphia, Pennsylvania",
                      "Phoenix, Arizona",
                      "San Antonio, Texas",
                      "San Diego, California",
                      "Dallas, Texas",
                      "San Jose, California",
                      "Austin, Texas",
                      "Jacksonville, Florida",
                      "Indianapolis, Indiana",
                      "San Francisco, California",
                      "Columbus, Ohio",
                      "Fort Worth, Texas",
                      "Charlotte, North Carolina",
                      "Detroit, Michigan",
                      "El Paso, Texas",
                      "Memphis, Tennessee",
                      "Boston, Massachusetts",
                      "Seattle, Washington",
                      "Denver, Colorado",
                      "Washington, DC",
                      "Nashville-Davidson, Tennessee",
                      "Baltimore, Maryland",
                      "Louisville/Jefferson, Kentucky",
                      "Portland, Oregon",
                      "Oklahoma , Oklahoma",
                      "Milwaukee, Wisconsin",
                      "Las Vegas, Nevada",
                      "Albuquerque, New Mexico",
                      "Tucson, Arizona",
                      "Fresno, California",
                      "Sacramento, California",
                      "Long Beach, California",
                      "Kansas , Missouri",
                      "Mesa, Arizona",
                      "Virginia Beach, Virginia",
                      "Atlanta, Georgia",
                      "Colorado Springs, Colorado",
                      "Raleigh, North Carolina",
                      "Omaha, Nebraska",
                      "Miami, Florida",
                      "Oakland, California",
                      "Tulsa, Oklahoma",
                      "Minneapolis, Minnesota",
                      "Cleveland, Ohio",
                      "Wichita, Kansas",
                      "Arlington, Texas",
                      "New Orleans, Louisiana",
                      "Bakersfield, California",
                      "Tampa, Florida",
                      "Honolulu, Hawaii",
                      "Anaheim, California",
                      "Aurora, Colorado",
                      "Santa Ana, California",
                      "St. Louis, Missouri",
                      "Riverside, California",
                      "Corpus Christi, Texas",
                      "Pittsburgh, Pennsylvania",
                      "Lexington-Fayette, Kentucky",
                      "Anchorage, Alaska",
                      "Stockton, California",
                      "Cincinnati, Ohio",
                      "St. Paul, Minnesota",
                      "Toledo, Ohio",
                      "Newark, New Jersey",
                      "Greensboro, North Carolina",
                      "Plano, Texas",
                      "Henderson, Nevada",
                      "Lincoln, Nebraska",
                      "Buffalo, New York",
                      "Fort Wayne, Indiana",
                      "Jersey , New Jersey",
                      "Chula Vista, California",
                      "Orlando, Florida",
                      "St. Petersburg, Florida",
                      "Norfolk, Virginia",
                      "Chandler, Arizona",
                      "Laredo, Texas",
                      "Madison, Wisconsin",
                      "Durham, North Carolina",
                      "Lubbock, Texas",
                      "Winston-Salem, North Carolina",
                      "Garland, Texas",
                      "Glendale, Arizona",
                      "Hialeah, Florida",
                      "Reno, Nevada",
                      "Baton Rouge, Louisiana",
                      "Irvine, California",
                      "Chesapeake, Virginia",
                      "Irving, Texas",
                      "Scottsdale, Arizona",
                      "North Las Vegas, Nevada",
                      "Fremont, California",
                      "Gilbert town, Arizona",
                      "San Bernardino, California",
                      "Boise, Idaho",
                      "Birmingham, Alabama",
                      "Montréal",
                      "Vancouver",
                      "Ottawa",
                      "Edmonton",
                      "Calgary",
                      "Quebéc",
                      "Winnipeg",
                      "Hamilton",
                      "London",
                      "Kitchener",
                      "St Catharines-Niagara",
                      "Halifax",
                      "Victoria",
                      "Windsor",
                      "Oshawa",
                      "Saskatoon",
                      "Regina",
                      "St John's",
                      "Sudbury",
                      "Chicoutimi",
                      "Sherbrooke",
                      "Kingston",
                      "Trois-Rivières",
                      "Kelowna",
                      "Abbotsford",
                      "Saint John",
                      "Thunder Bay",
                      "Barrie",
                      "Sydney",
                      "London",
                      "Birmingham",
                      "Leeds",
                      "Glasgow",
                      "Sheffield",
                      "Bradford",
                      "Liverpool",
                      "Edinburgh",
                      "Manchester",
                      "Bristol",
                      "Kirklees",
                      "Fife",
                      "Wirral",
                      "North Lanarkshire",
                      "Wakefield",
                      "Cardiff",
                      "Dudley",
                      "Wigan",
                      "East Riding",
                      "South Lanarkshire",
                      "Coventry",
                      "Belfast",
                      "Leicester",
                      "Sunderland",
                      "Sandwell",
                      "Doncaster",
                      "Stockport",
                      "Sefton",
                      "Nottingham",
                      "Newcastle-upon-Tyne",
                      "Kingston-upon-Hull",
                      "Bolton",
                      "Walsall",
                      "Plymouth",
                      "Rotherham",
                      "São Paulo, Brazil",
                      "Bombay, India",
                      "Jakarta, Indonesia",
                      "Karachi, Pakistan",
                      "Moscow, Russia",
                      "Istanbul, Turkey",
                      "(Mexico City), Mexico",
                      "Shanghai, China",
                      "Tokyo, Japan",
                      "BANGKOK, Thailand",
                      "Beijing, China",
                      "Delhi, India",
                      "London, UK",
                      "HongKong, China",
                      "Cairo, Egypt",
                      "Tehran, Iran",
                      "Bogota, Colombia",
                      "Bandung, Indonesia",
                      "Tianjin, China",
                      "LIMA, Peru",
                      "Rio de Janeiro, Brazil",
                      "Lahore, Pakistan",
                      "Bogor, Indonesia",
                      "Santiago, Chile",
                      "St Petersburg, Russia",
                      "Shenyang, China",
                      "Calcutta, India",
                      "Wuhan, China",
                      "Sydney, Australia",
                      "Guangzhou, China",
                      "Singapore",
                      "Madras, India",
                      "Baghdad, Iraq",
                      "Pusan, South Korea",
                      "Yokohama, Japan",
                      "Dhaka, Bangladesh",
                      "Berlin, Germany"]
        return cities.randomElement() ?? "New York, New York"
    }
}
