//
//  Random.swift
//  screenshot
//
//  Created by Jonathan Rose on 4/11/18.
//  Copyright © 2018 crazeapp. All rights reserved.
//

import Foundation

extension Collection where Index == Int {
    
    /**
     Picks a random element of the collection.
     
     - returns: A random element of the collection.
     */
    func randomElement() -> Iterator.Element? {
        return isEmpty ? nil : self[Int(arc4random_uniform(UInt32(endIndex)))]
    }
}

extension String {
    static func randomFemaleName() -> String{
        let femaleNames = ["Aaliyah",
                           "Abigail",
                           "Abigail",
                           "Adalyn",
                           "Addison",
                           "Adeline",
                           "Alexa",
                           "Alexis",
                           "Alexis",
                           "Alice",
                           "Allison",
                           "Alyssa",
                           "Amanda",
                           "Amber",
                           "Amelia",
                           "Amy",
                           "Andrea",
                           "Angela",
                           "Ann",
                           "Anna",
                           "Anna",
                           "Anna",
                           "Aria",
                           "Ariana",
                           "Ariel",
                           "Ashlee",
                           "Ashley",
                           "Aubree",
                           "Aubrey",
                           "Audrey",
                           "Autumn",
                           "Avery",
                           "Bailey",
                           "Barbara",
                           "Becca",
                           "Becky ",
                           "Bella",
                           "Bella",
                           "Betty",
                           "Beverly",
                           "Blakely",
                           "Brenda",
                           "Brittany",
                           "Brook",
                           "Carol",
                           "Caroline",
                           "Carolyn",
                           "Catherine",
                           "Charlotte",
                           "Cheryl",
                           "Chloe",
                           "Christina",
                           "Christine",
                           "Claire",
                           "Cynthia",
                           "Danielle",
                           "Debbie",
                           "Debra",
                           "Denise",
                           "Diana",
                           "Diane",
                           "Donna",
                           "Doris",
                           "Eleanor",
                           "Elizabeth",
                           "Elizabeth",
                           "Ella",
                           "Ellie",
                           "Emily",
                           "Emily",
                           "Emma",
                           "Emma",
                           "Evelyn",
                           "Evelyn",
                           "Gloria",
                           "Grace",
                           "Grace",
                           "Hadley",
                           "Hannah",
                           "Hannah",
                           "Harmony",
                           "Harper",
                           "Heather",
                           "Helen",
                           "Isabella",
                           "Jacqueline",
                           "Jane",
                           "Janet",
                           "Janice",
                           "Jean",
                           "Jennifer",
                           "Jessica",
                           "Joan",
                           "Jordyn",
                           "Joyce",
                           "Judy",
                           "Judy",
                           "Julia",
                           "Julie",
                           "Karen",
                           "Karen",
                           "Katherine",
                           "Katherine",
                           "Kathleen",
                           "Kathryn",
                           "Kayla",
                           "Kaylee",
                           "Kelly",
                           "Kelsey ",
                           "Kennedy",
                           "Khloe",
                           "Kim ",
                           "Kimberly",
                           "Kinsley",
                           "Kyleigh",
                           "Kylie",
                           "Laila",
                           "Laura",
                           "Lauren",
                           "Layla",
                           "Leah",
                           "Lillian",
                           "Lilly",
                           "Lily",
                           "Linda",
                           "Lisa",
                           "Lizzy",
                           "London",
                           "Lori",
                           "Lucy",
                           "Lydia",
                           "Madelyn",
                           "Madison",
                           "Madison",
                           "Margaret",
                           "Margaret",
                           "Maria",
                           "Mariah",
                           "Marie",
                           "Marilyn",
                           "Martha",
                           "Mary",
                           "Maya",
                           "Mckenzie",
                           "Megan",
                           "Melissa",
                           "Mia",
                           "Michelle",
                           "Morgan",
                           "Nancy",
                           "Naomi",
                           "Natalie",
                           "Natalie",
                           "Nicole",
                           "Nikki ",
                           "Nora",
                           "Olivia",
                           "Olivia",
                           "Paisley",
                           "Pamela",
                           "Patricia",
                           "Penelope",
                           "Peyton",
                           "Piper",
                           "Rachel",
                           "Raelynn",
                           "Rebecca",
                           "Riley",
                           "Rose",
                           "Ruby",
                           "Ruth",
                           "Rylee",
                           "Ryleigh",
                           "Sadie",
                           "Samantha",
                           "Sandra",
                           "Sara",
                           "Sara",
                           "Sarah",
                           "Sarah",
                           "Savannah",
                           "Scarlett",
                           "Sharon",
                           "Shirley",
                           "Skylar",
                           "Sofia",
                           "Sophia",
                           "Stella",
                           "Stephanie",
                           "Susan",
                           "Taylor",
                           "Teresa",
                           "Theresa",
                           "Tiffany",
                           "Victoria",
                           "Victoria",
                           "Willow",
                           "Zoe",
                           "Zoey",
                           "Noah ",
                           "Olivia",
                           "Emma",
                           "Sophia",
                           "Mia",
                           "Ava",
                           "Emily",
                           "Abigail",
                           "Sofia",
                           "Amelia",
                           "Charlotte",
                           "Victoria",
                           "Madison",
                           "Elizabeth",
                           "Harper",
                           "Ella",
                           "Riley",
                           "Aria",
                           "Chloe",
                           "Leah",
                           "Lily",
                           "Valentina",
                           "Gabriella",
                           "Layla",
                           "Zoey",
                           "Aaliyah",
                           "Camila",
                           "Avery",
                           "Penelope",
                           "Skylar",
                           "Scarlett",
                           "Savannah",
                           "Zoe",
                           "Mila",
                           "Samantha",
                           "Grace",
                           "Aubrey",
                           "Ariana",
                           "Sarah",
                           "Evelyn",
                           "Arianna",
                           "Luna",
                           "Natalie",
                           "Addison",
                           "Polly ",
                           "Hannah",
                           "Lillian",
                           "Gianna",
                           "Stella",
                           "Alexa",
                           "Bella",
                           "Brooklyn",
                           "Ashley",
                           "Ellie",
                           "Audrey",
                           "Eva",
                           "Allison",
                           "Brianna",
                           "Serenity",
                           "Nevaeh",
                           "Aurora",
                           "Maya",
                           "Kylie",
                           "Maria",
                           "Melanie",
                           "Naomi",
                           "Mackenzie",
                           "Angelina",
                           "Taylor",
                           "Violet",
                           "Faith",
                           "Kennedy",
                           "Jasmine",
                           "Autumn",
                           "Emilia",
                           "Peyton",
                           "Sadie",
                           "Alice",
                           "Nicole",
                           "Paisley",
                           "Elena",
                           "Julia",
                           "Annabelle",
                           "Hailey",
                           "Jade",
                           "Kaylee",
                           "Anna",
                           "Madelyn",
                           "Adeline",
                           "Alexandra",
                           "Brielle",
                           "Katherine",
                           "London",
                           "Caroline",
                           "Piper",
                           "Kinsley",
                           "Eliana",
                           "Natalia",
                           "Alyssa",
                           "Nora",
                           "Rikki",
                           "Katie"]
        return femaleNames.randomElement() ?? "Molly"
    }
    static func randomMaleName() -> String{
        let maleNames = [
            "John",
            "Robert",
            "Michael",
            "Will",
            "David",
            "Richard",
            "Joseph",
            "Tom",
            "Charlie",
            "Christopher",
            "Daniel",
            "Matthew",
            "Anthony",
            "Liam",
            "Mark",
            "Paul",
            "Steven",
            "Andrew",
            "Ken",
            "George",
            "Josh",
            "Kevin",
            "Brian",
            "Edward",
            "Ronald",
            "Timothy",
            "Jason",
            "Jeffrey",
            "Ryan",
            "Gary",
            "Jacob",
            "Nick",
            "Eric",
            "Stephen",
            "Jonathan",
            "Larry",
            "Justin",
            "Scott",
            "Frank",
            "Brandon",
            "Raymond",
            "Greg",
            "Benjamin",
            "Sammy",
            "Patrick",
            "Alexander",
            "Jack",
            "Dennis",
            "Jerry",
            "Tyler",
            "Aaron",
            "Henry",
            "Douglas",
            "Jose",
            "Peter",
            "Adam",
            "Zachary",
            "Nathan",
            "Walter",
            "Harry",
            "Kyle",
            "Carl",
            "Arthur",
            "Noah",
            "Roger",
            "Keith",
            "Jeremy",
            "Terry",
            "Lawrence",
            "Sean",
            "Christian",
            "Albert",
            "Joe",
            "Ethan",
            "Austin",
            "Jesse",
            "Willie",
            "Billy",
            "Bryan",
            "Bruce",
            "Jordan",
            "Ralph",
            "Roy",
            "Noah",
            "Dylan",
            "Eugene",
            "Wayne",
            "Alan",
            "Juan",
            "Louis",
            "Russell",
            "Gabriel",
            "Randy",
            "Philip",
            "Harry",
            "Bobby",
            "Johnny",
            "Logan",
            "Johnny ",
            "Danny ",
            "Matt"]
        return maleNames.randomElement() ?? "Matt"

    }
    static func randomName() -> String{
        let percentFemale:Double = 0.8
        let max = 10000
        
        let isFemale = (arc4random_uniform(10000) < Int(Double(max) * percentFemale))
        if isFemale {
            return String.randomFemaleName()
        }else{
            return String.randomMaleName()
        }
    }
    static func randomCity() -> String{
        let cities = ["New York, New York",
                      "Los Angeles, California",
                      "Chicago, Illinois",
                      "Houston, Texas",
                      "Philadelphia, Pennsylvania",
                      "Phoenix, Arizona",
                      "San Antonio, Texas",
                      "San Diego, California",
                      "Dallas, Texas",
                      "San Jose, California",
                      "Austin, Texas",
                      "Jacksonville, Florida",
                      "Indianapolis, Indiana",
                      "San Francisco, California",
                      "Columbus, Ohio",
                      "Fort Worth, Texas",
                      "Charlotte, North Carolina",
                      "Detroit, Michigan",
                      "El Paso, Texas",
                      "Memphis, Tennessee",
                      "Boston, Massachusetts",
                      "Seattle, Washington",
                      "Denver, Colorado",
                      "Washington, DC",
                      "Nashville-Davidson, Tennessee",
                      "Baltimore, Maryland",
                      "Louisville/Jefferson, Kentucky",
                      "Portland, Oregon",
                      "Oklahoma , Oklahoma",
                      "Milwaukee, Wisconsin",
                      "Las Vegas, Nevada",
                      "Albuquerque, New Mexico",
                      "Tucson, Arizona",
                      "Fresno, California",
                      "Sacramento, California",
                      "Long Beach, California",
                      "Kansas , Missouri",
                      "Mesa, Arizona",
                      "Virginia Beach, Virginia",
                      "Atlanta, Georgia",
                      "Colorado Springs, Colorado",
                      "Raleigh, North Carolina",
                      "Omaha, Nebraska",
                      "Miami, Florida",
                      "Oakland, California",
                      "Tulsa, Oklahoma",
                      "Minneapolis, Minnesota",
                      "Cleveland, Ohio",
                      "Wichita, Kansas",
                      "Arlington, Texas",
                      "New Orleans, Louisiana",
                      "Bakersfield, California",
                      "Tampa, Florida",
                      "Honolulu, Hawaii",
                      "Anaheim, California",
                      "Aurora, Colorado",
                      "Santa Ana, California",
                      "St. Louis, Missouri",
                      "Riverside, California",
                      "Corpus Christi, Texas",
                      "Pittsburgh, Pennsylvania",
                      "Lexington-Fayette, Kentucky",
                      "Anchorage municipality, Alaska",
                      "Stockton, California",
                      "Cincinnati, Ohio",
                      "St. Paul, Minnesota",
                      "Toledo, Ohio",
                      "Newark, New Jersey",
                      "Greensboro, North Carolina",
                      "Plano, Texas",
                      "Henderson, Nevada",
                      "Lincoln, Nebraska",
                      "Buffalo, New York",
                      "Fort Wayne, Indiana",
                      "Jersey , New Jersey",
                      "Chula Vista, California",
                      "Orlando, Florida",
                      "St. Petersburg, Florida",
                      "Norfolk, Virginia",
                      "Chandler, Arizona",
                      "Laredo, Texas",
                      "Madison, Wisconsin",
                      "Durham, North Carolina",
                      "Lubbock, Texas",
                      "Winston-Salem, North Carolina",
                      "Garland, Texas",
                      "Glendale, Arizona",
                      "Hialeah, Florida",
                      "Reno, Nevada",
                      "Baton Rouge, Louisiana",
                      "Irvine, California",
                      "Chesapeake, Virginia",
                      "Irving, Texas",
                      "Scottsdale, Arizona",
                      "North Las Vegas, Nevada",
                      "Fremont, California",
                      "Gilbert town, Arizona",
                      "San Bernardino, California",
                      "Boise, Idaho",
                      "Birmingham, Alabama",
                      "Montréal",
                      "Vancouver",
                      "Ottawa",
                      "Edmonton",
                      "Calgary",
                      "Quebéc",
                      "Winnipeg",
                      "Hamilton",
                      "London",
                      "Kitchener",
                      "St Catharines-Niagara",
                      "Halifax",
                      "Victoria",
                      "Windsor",
                      "Oshawa",
                      "Saskatoon",
                      "Regina",
                      "St John's",
                      "Sudbury",
                      "Chicoutimi",
                      "Sherbrooke",
                      "Kingston",
                      "Trois-Rivières",
                      "Kelowna",
                      "Abbotsford",
                      "Saint John",
                      "Thunder Bay",
                      "Barrie",
                      "Sydney",
                      "London",
                      "Birmingham",
                      "Leeds",
                      "Glasgow",
                      "Sheffield",
                      "Bradford",
                      "Liverpool",
                      "Edinburgh",
                      "Manchester",
                      "Bristol",
                      "Kirklees",
                      "Fife",
                      "Wirral",
                      "North Lanarkshire",
                      "Wakefield",
                      "Cardiff",
                      "Dudley",
                      "Wigan",
                      "East Riding",
                      "South Lanarkshire",
                      "Coventry",
                      "Belfast",
                      "Leicester",
                      "Sunderland",
                      "Sandwell",
                      "Doncaster",
                      "Stockport",
                      "Sefton",
                      "Nottingham",
                      "Newcastle-upon-Tyne",
                      "Kingston-upon-Hull",
                      "Bolton",
                      "Walsall",
                      "Plymouth",
                      "Rotherham",
                      "São Paulo, Brazil",
                      "Bombay, India",
                      "Jakarta, Indonesia",
                      "Karachi, Pakistan",
                      "Moscow, Russia",
                      "Istanbul, Turkey",
                      "(Mexico City), Mexico",
                      "Shanghai, China",
                      "Tokyo, Japan",
                      "BANGKOK, Thailand",
                      "Beijing, China",
                      "Delhi, India",
                      "London, UK",
                      "HongKong, China",
                      "Cairo, Egypt",
                      "Tehran, Iran",
                      "Bogota, Colombia",
                      "Bandung, Indonesia",
                      "Tianjin, China",
                      "LIMA, Peru",
                      "Rio de Janeiro, Brazil",
                      "Lahore, Pakistan",
                      "Bogor, Indonesia",
                      "Santiago, Chile",
                      "St Petersburg, Russia",
                      "Shenyang, China",
                      "Calcutta, India",
                      "Wuhan, China",
                      "Sydney, Australia",
                      "Guangzhou, China",
                      "Singapore",
                      "Madras, India",
                      "Baghdad, Iraq",
                      "Pusan, South Korea",
                      "Yokohama, Japan",
                      "Dhaka, Bangladesh",
                      "Berlin, Germany"]
        return cities.randomElement() ?? "New York, New York"
    }
}
